# -*- coding: utf-8 -*-
"""Parsing XML and URL and writing in file

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1npsQeYe-f88SGl3jQkDI6IbDp3l4Zl6P
"""

import requests
import re
import os,sys
import subprocess
import glob
from os import path

def find(sites,text,filename,flag):
    url=sites
    #print("\nURL:", url) 
    r = requests.get(url)
    page_source = r.text
    page_source = page_source.split('\n')
    term =text 
    k=0
    #page_source =['ctl00_ContentPlaceHolder1_PICList_gridPICList__1IUWHKWJR target','ctl00_ContentPlaceHolder1_PICList_gridPICList__1']
    for row in page_source[:]:
        print(row)
        if  re.search( term,row)  :
          if flag=='none' :
            finalurl1= 'Search String Found URL '+filename +'\n'+ 'rows'+row
            print(finalurl1)
            #with open(filename, 'a') as f:
              #print(finalurl1, file=f)        
          else :
            x=row.split('href=\"')[1].split('\"')[0]  
            finalurl1='https://fsims.faa.gov/'+x.replace(' ','%20')
  
         
sites =   'https://fsims.faa.gov/PICResults.aspx?mode=Publication&doctype=SAS%20DCT'

term= 'target="FSIMS_Document_Viewer"'
#find(sites,term,'file.txt','split')
term='AC-120-58, AC-120-60, A023, 8900.1'
with open('file.txt', 'r') as f:
  #rows=f.read()
  rows='https://fsims.faa.gov/PICDetail.aspx?docId=EP%206.4.1%20135B%20AW%206.0'
  for row in rows :
   #print(row)
   find(x,term,'output.txt','none')
  #print(f.read())
f.close()
print("-------------------------------------")

"""# New Section

# New Section
"""

from google.colab import drive
drive.mount('/content/drive')